# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-top', '-modify_time']},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default=b'onion', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.CharField(blank=True, default=b'blog_default.png', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='reads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.CharField(choices=[(b't', '\u7f6e\u9876'), (b'g', '\u4e00\u822c')], default=b'g', max_length=1, verbose_name='\u7f6e\u9876'),
        ),
    ]
